### ISSUE TITLE
Invalid arg type The "path" argument must be one of type string, Buffer or URL. Received type number.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [ozra/mmap-io#20]
Ran the example use in readme through a livescript to js compile on here http://livescript.net/

node v10.14.1 Windows 10 has an error running sample code.

```
internal/fs/utils.js:453
    throw err;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type number
    at Object.statSync (fs.js:844:3)
    at Object.<anonymous> (E:\mmap\index.js:8:11)
```

Code:
```js
var mmap, fs, someFile, fd, fdW, size, rxProt, priv, buffer, buffer2, wBuffer, coreStats;
mmap = require("mmap-io");
fs = require("fs");

someFile = "./foo.bar";
fd = fs.openSync(someFile, "r");
fdW = fs.openSync(someFile, "r+");
size = fs.statSync(fd).size; // This line has the error.

rxProt = mmap.PROT_READ | mmap.PROT_EXECUTE;
priv = mmap.MAP_SHARED;
buffer = mmap.map(size, rxProt, priv, fd);


buffer2 = mmap.map(size, mmap.PROT_READ, priv, fd, 0, mmap.MADV_SEQUENTIAL);

wBuffer = mmap.map(size, mmap.PROT_WRITE, priv, fdW);

mmap.advise(wBuffer, mmap.MADV_RANDOM);

mmap.sync(wBuffer);
mmap.sync(wBuffer, true);
mmap.sync(wBuffer, 0, size);
mmap.sync(wBuffer, 0, size, true);
mmap.sync(wBuffer, 0, size, true, false);

coreStats = mmap.incore(buffer);
```

fs.openSync
> Returns an integer representing the file descriptor.

https://stackoverflow.com/questions/16106111/how-to-get-file-descriptor-in-node-js-if-you-open-file-using-opensync

Need to use fs.fstatSync

**Comment by ozra** [comment]
I added in your fix, thanks.
